apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-helloworld
  labels:
    app: argocd-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-helloworld
  template:
    metadata:
      labels:
        app: argocd-helloworld
    spec:
      containers:
        - name: go-hello-http
          image: "{{ .Values.image.repository }}:{{ default .Values.image.tag }}"
          ports:
            - containerPort: 80
